Fix primary button disabled color and icon button
decent-dao/decent-ui pull request #97
Opened 2024-05-10 22:05 UTC by mudrila

## Overview 
Adjust disabled button color for primary button, add styles for icon button, fix disabled color for input

## Changes
- Change `disabled` state color for `primary` `Button`
- Define styles for `IconButton`
- Change `disabled` state color for `Input` to `neutral-6` so that it's brighter than placeholder but still not too bright to visualize different state

## Screenshots
If applicable, provide any necessary screenshots with updates to the UI

## Notes
Design: https://www.figma.com/file/ur5hElxplkmlY9gnGKlwrm/Components-%26-Styles---Decent-Design-System-1.0.0?node-id=288-15125&mode=dev

Related to https://github.com/decentdao/fractal-interface/issues/1693 and https://github.com/decentdao/fractal-interface/issues/1682

## Checklist
- [ ]  Ran all tests and manually tested for bugs
- [ ]  Has tested that app successfully builds/starts locally
- [ ]  Has tested that PR deployment (on develop) has been successful
- [ ]  Call out (review comment) and explain new code changes that may not be self-explainatory (when in doubt, leave a comment)
- [ ]  Call out (review comment) any incomplete code, or code that was added as a shim to complete the PR.
- [ ]  Call out (review comment) code that is hacky or will need to be refactored later.

2024-05-11 03:17 UTC, adamgall commented
I don't really know how to review this code! Would love if @Da-Colon could do a live review with me.

2024-05-11 04:01 UTC, Da-Colon commented on design/tokens/components/iconButton/theme/iconButton.sizes.ts
> +  }
![image](https://github.com/decentdao/decent-ui/assets/38386583/4b316ae3-9db2-4083-b058-13309ba72c80)

The sm icon seems like the padding is off. This was tricky with the IconButton as the width and height properties are for the `Button` with the SVG just being relative to that.

2024-05-11 04:04 UTC, Da-Colon requested changes
The comment applies to all three sizes. @adamgall and I were actually messing with this ealier this evening and found it was much easier to just use the `Icon` as a child to the `Button` than trying to style the `IconButton` component.

We spoke about creating a `icon` size in the `buttons.sizes.ts` to allow for adjustments for the `Button` component with a `Icon` child.

that being said. if you can figure it out how to tweak it to get the padding and size of `IconButton` to match the figma, go for it. ha

2024-05-11 18:38 UTC, mudrila commented
@Da-Colon @adamgall 
Here you go 
<img width="1676" alt="Знімок екрана 2024-05-11 о 20 38 10" src="https://github.com/decentdao/decent-ui/assets/25801162/11f5de91-ba0d-4690-9b96-c76607b82c0b">

2024-05-11 18:43 UTC, mudrila commented
@adamgall If you wanna test these changes - follow these steps

1. Run `nvm use`
2. Run `npm install`
3. Run `npm run storybook`

This will run Storybook on `localhost:6006`, on the left side there will be components list and you can check `IconButton` component.

@Da-Colon @adamgall There's a little hack - I'm not using `padding` in sizes, essentially it's not applied and always overwritten with `padding: 0` for whoknows which reason. So I'm just playing with icon size properly

2024-05-11 22:23 UTC, mudrila commented
@adamgall @Da-Colon @DarksightKellar I also pushed a fix for https://github.com/decentdao/fractal-interface/issues/1749 into this branch

2024-05-14 00:01 UTC, Da-Colon approved these changes
Good deal, LGTM, ship it

2024-05-14 08:32 UTC, mudrila commented
Gonna merge now to unblock fixes that relying on these changes

2024-05-14 08:32 UTC, merged